- [ ] Import libraries
- [ ] Quantum states and density matrises
- [ ] Quantum operators
- [ ] Composite systems 

# Import libraries

In [1]:
import numpy as np 
import matplotlib.pyplot as plt 
import qutip as qt

# Quantum states and density matrises

### Fock states

In [3]:
# number of states in the Hilbert space 
N = 4;
#  occupied state
n = 1;
qt.basis(N,n)   # equivalent to fock(N, n)

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]]

In [4]:
qt.fock(N,n)

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]]

### coherent state

In [6]:
qt.coherent(N=4,alpha=1.0)

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[0.60605894]
 [0.6100857 ]
 [0.41242505]
 [0.30065525]]

In [7]:
# My Q
# what are coherent states? 
# what are the most important differences between coherent states and other states (such as fock)

### Density matrices

In [8]:
qt.fock_dm(4,1)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

In [9]:
qt.coherent_dm(4,1.0)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.36730744 0.36974789 0.24995389 0.1822148 ]
 [0.36974789 0.37220456 0.25161463 0.18342547]
 [0.24995389 0.25161463 0.17009442 0.12399776]
 [0.1822148  0.18342547 0.12399776 0.09039358]]

In [ ]:
# What are thermal states? 
# What does "average number of thermal photons" var do? 
# why thermal states do not have states??? 

In [10]:
# thermal states 
nt = 1;   # average number of thermal photons
qt.thermal_dm(8,n)

Quantum object: dims = [[8], [8]], shape = (8, 8), type = oper, isherm = True
Qobj data =
[[0.50196078 0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.25098039 0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.1254902  0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.0627451  0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.03137255 0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.01568627
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.00784314 0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.00392157]]

## Quantum operators

### Qubit operator

In [12]:
# Pauli operators 
qt.sigmax()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 1.]
 [1. 0.]]

In [13]:
qt.sigmay()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j]]

In [14]:
qt.sigmaz()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

In [15]:
# Pauli spin's creation and annihilation operator
qt.sigmap()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[0. 1.]
 [0. 0.]]

In [16]:
qt.sigmam()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[0. 0.]
 [1. 0.]]

### Harmonic oscillator operators

In [17]:
# annihilation operator 
qt.destroy(N = 4) # N = number of fock states included in the Hilbert space

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.         1.         0.         0.        ]
 [0.         0.         1.41421356 0.        ]
 [0.         0.         0.         1.73205081]
 [0.         0.         0.         0.        ]]

In [19]:
# creation operator
qt.create(N=4) # equivalent to destroy(N=4).dag()

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.         0.         0.         0.        ]
 [1.         0.         0.         0.        ]
 [0.         1.41421356 0.         0.        ]
 [0.         0.         1.73205081 0.        ]]

In [20]:
# Example 
# create position operator 
a = qt.destroy(4)
ad = a.dag()
x = a + ad
x

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.         1.         0.         0.        ]
 [1.         0.         1.41421356 0.        ]
 [0.         1.41421356 0.         1.73205081]
 [0.         0.         1.73205081 0.        ]]

In [21]:
# commutator of two operators 
qt.commutator(a,ad)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0. -3.]]

$$
[X,P] = i
$$

In [25]:
X = (a + ad)/np.sqrt(2);
P = -1j*(a - ad)/np.sqrt(2);
qt.commutator(X,P)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.+1.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+1.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+1.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.-3.j]]

In [22]:
# qutip have truncated the Hilbert space 
# The highest Fock state is not involved in the dynamics (in qutip's truncated HS) 

Let's check if 
$$
[\sigma_x , \sigma_y] = 2i\sigma_z
$$

In [26]:
qt.commutator(qt.sigmax() , qt.sigmay()) - 2j*qt.sigmaz()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 0.]
 [0. 0.]]

In [28]:
# Multiplication and power of Pauli's operators
-1j * qt.sigmax() * qt.sigmay() * qt.sigmaz()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]

In [31]:
qt.sigmax() **2 == qt.sigmay() **2 == qt.sigmaz()**2 == qt.qeye(2)

True

## Composite systems 

$$
\sigma_z \otimes I
$$

In [33]:
sz1 = qt.tensor(qt.sigmaz(), qt.qeye(2))
sz1

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0. -1.]]

In [35]:
sz2 = qt.tensor(qt.qeye(2), qt.sigmaz())
sz2 

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 1.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0. -1.]]

In [36]:
ψ1 = qt.tensor(qt.basis(2,1), qt.basis(2,0))
ψ2 = qt.tensor(qt.basis(2,0), qt.basis(2,1))

In [40]:
sz1 *ψ1 == ψ1

False

In [41]:
sz1 * ψ2 == ψ2 

True